#' Generate Color Palettes
#'
#' This function creates a list of predefined color palettes.
#'
#' @return A list of approved c4cp color palettes, each containing a vector
#'  of color hex codes.
#' @export
#' @noRd
#' @examples
#' palettes <- color_palette()
color_palette <- function(){
  c <- list(
    blue = c("#2973A5", "#648EB4", "#8BAAC7", "#B1C7D9", "#D8E3EC"),
    darkblue = c("#164C71", "#51708A", "#7C94A8", "#A8B7C5", "#D3DBE2"),
    yellow = c("#FDBE19", "#F6CC6C", "#F8D991", "#FBE5B5", "#FDF2DA"),
    skyblue = c("#309EBD", "#74B0C7", "#97C4D5", "#B9D7E3", "#DDECF1"),
    turq = c("#3C989E", "#77ACB0", "#99C0C4", "#BBD5D7", "#DDEAEC"),
    grey = c("#565C65", "#797D83", "#9A9DA3", "#BBBEC1", "#DDDEE0"),
    brown = c("#CC7D15", "#CD995B", "#DAB384", "#E7CCAD", "#F3E6D6")
  )
}

#' Select Colors from Palette
#'
#' This function selects a specified number of colors from the
#' c4cp color palette.
#'
#' @param palette A list of color palettes generated by \code{color_palette()}.
#' @param num_series An integer specifying the number of colors to select.
#'
#' @return A character vector of selected color hex codes.
#' @export
#'
#' @examples
#' palettes <- color_palette()
#' selected <- select_colors(palettes, 10)
#' plot(x,y, col = selected[1])
select_colors <- function(palette, num_series) {
  # Initialize an empty vector to store the selected colors
  selected_colors <- character(num_series)

  # Get the number of color groups and the maximum number of shades
  num_groups <- length(palette)
  max_shades <- max(sapply(palette, length))

  # Loop through each shade level and then each color group to fill the selected_colors
  counter <- 1
  for (shade in 1:max_shades) {
    for (group in 1:num_groups) {
      current_palette <- palette[[group]]
      if (length(current_palette) >= shade && counter <= num_series) {
        selected_colors[counter] <- current_palette[shade]
        counter <- counter + 1
      }
    }
  }

  return(selected_colors)
}
